"""Realistic seed data: 8 companies, 36 jobs, demo accounts, applications."""
from __future__ import annotations

CATEGORIES = [
    "IT", "Design", "SMM", "Marketing", "Sales", "Finance",
    "Education", "Support", "Media", "HR", "Operations", "Logistics", "Hospitality",
]

POPULAR_CATEGORIES = [
    {"key": "IT", "label_uz": "IT va dasturlash", "label_en": "IT & Development", "label_ru": "IT и разработка", "icon": "code", "count": 7},
    {"key": "Design", "label_uz": "Dizayn", "label_en": "Design", "label_ru": "Дизайн", "icon": "palette", "count": 4},
    {"key": "SMM", "label_uz": "SMM", "label_en": "SMM", "label_ru": "SMM", "icon": "megaphone", "count": 3},
    {"key": "Marketing", "label_uz": "Marketing", "label_en": "Marketing", "label_ru": "Маркетинг", "icon": "trending-up", "count": 3},
    {"key": "Sales", "label_uz": "Savdo", "label_en": "Sales", "label_ru": "Продажи", "icon": "handshake", "count": 3},
    {"key": "Finance", "label_uz": "Moliya", "label_en": "Finance", "label_ru": "Финансы", "icon": "landmark", "count": 2},
    {"key": "Education", "label_uz": "Ta'lim", "label_en": "Education", "label_ru": "Образование", "icon": "graduation-cap", "count": 3},
    {"key": "Support", "label_uz": "Mijozlar bilan ishlash", "label_en": "Customer Support", "label_ru": "Поддержка клиентов", "icon": "headphones", "count": 3},
]

LOCATIONS = ["Tashkent", "Samarkand", "Bukhara", "Andijan", "Namangan", "Fergana", "Nukus", "Remote"]

EMPLOYMENT_TYPES = ["Full-time", "Part-time", "Contract", "Freelance", "Internship", "Remote"]
EXPERIENCE_LEVELS = ["No experience", "Junior", "Middle", "Senior"]

COMPANIES = [
    {
        "name": "TechNova Solutions", "slug": "technova-solutions", "industry": "Software Development",
        "location": "Tashkent", "size": "120-200 employees", "website": "https://technova.uz",
        "logo": "TN", "color": "#1D4ED8", "verified": True,
        "about": "TechNova Solutions builds fintech and e-commerce products for Central Asia. We ship software used by millions of users and invest heavily in our engineers' growth, mentorship and modern tooling.",
    },
    {
        "name": "PixelCraft Studio", "slug": "pixelcraft-studio", "industry": "Design & Creative",
        "location": "Tashkent", "size": "25-50 employees", "website": "https://pixelcraft.uz",
        "logo": "PC", "color": "#0EA5E9", "verified": True,
        "about": "PixelCraft is a design studio working with brands across the region: product design, brand identity and motion. We are a small senior team that cares deeply about craft and detail.",
    },
    {
        "name": "SilkRoute Logistics", "slug": "silkroute-logistics", "industry": "Logistics & Supply chain",
        "location": "Samarkand", "size": "300-500 employees", "website": "https://silkroute.uz",
        "logo": "SR", "color": "#0369A1", "verified": True,
        "about": "SilkRoute Logistics moves cargo across Central Asia and China. We combine a physical fleet with a modern digital operations platform to give clients transparent delivery.",
    },
    {
        "name": "UzDigital Marketing", "slug": "uzdigital-marketing", "industry": "Marketing & Advertising",
        "location": "Tashkent", "size": "50-100 employees", "website": "https://uzdigital.uz",
        "logo": "UD", "color": "#2563EB", "verified": True,
        "about": "UzDigital is a performance marketing agency running campaigns for local and international brands. We are data-driven, fast and results-obsessed.",
    },
    {
        "name": "Amu Finance Group", "slug": "amu-finance-group", "industry": "Financial services",
        "location": "Tashkent", "size": "100-250 employees", "website": "https://amufinance.uz",
        "logo": "AF", "color": "#1E40AF", "verified": True,
        "about": "Amu Finance Group provides accounting, audit and investment advisory services to more than 400 companies in Uzbekistan.",
    },
    {
        "name": "BrightMind Academy", "slug": "brightmind-academy", "industry": "Education & Training",
        "location": "Bukhara", "size": "40-80 employees", "website": "https://brightmind.uz",
        "logo": "BM", "color": "#0891B2", "verified": False,
        "about": "BrightMind Academy teaches English and IT to 3,000+ students per year across Bukhara and Samarkand with a modern blended-learning approach.",
    },
    {
        "name": "MedLine Care", "slug": "medline-care", "industry": "Healthcare services",
        "location": "Andijan", "size": "80-150 employees", "website": "https://medline.uz",
        "logo": "MC", "color": "#0284C7", "verified": False,
        "about": "MedLine Care operates a network of clinics and a 24/7 patient support line serving the Fergana valley.",
    },
    {
        "name": "Nexus Retail Group", "slug": "nexus-retail-group", "industry": "Retail & E-commerce",
        "location": "Namangan", "size": "200-400 employees", "website": "https://nexusretail.uz",
        "logo": "NR", "color": "#155E75", "verified": True,
        "about": "Nexus Retail Group runs a chain of stores and a fast-growing online marketplace with same-day delivery in 6 cities.",
    },
]

def _job(title, category, company, location, smin, smax, etype, exp, skills, description,
         responsibilities, requirements, benefits, days_ago, views, apps, remote=False, currency="UZS", period="month"):
    return {
        "title": title, "category": category, "company": company, "location": location,
        "salary_min": smin, "salary_max": smax, "employment_type": etype, "experience_level": exp,
        "skills": skills, "description": description, "responsibilities": responsibilities,
        "requirements": requirements, "benefits": benefits, "days_ago": days_ago,
        "views": views, "applications_count": apps, "is_remote": remote,
        "currency": currency, "salary_period": period,
    }


JOBS = [
    _job("Frontend Developer", "IT", "TechNova Solutions", "Tashkent", 12000000, 22000000, "Full-time", "Middle",
         ["React", "TypeScript", "Tailwind CSS", "REST API", "Git"],
         "We are looking for a Frontend Developer to build fast, accessible interfaces for our fintech products. You will work closely with designers and backend engineers in two-week sprints and own features from design hand-off to production.",
         ["Build and maintain React + TypeScript applications", "Collaborate with designers to implement pixel-accurate UI", "Optimise bundle size and Core Web Vitals", "Write unit tests and participate in code reviews"],
         ["2+ years of experience with React", "Strong TypeScript and modern CSS knowledge", "Experience consuming REST APIs", "Understanding of Git workflows"],
         ["Competitive salary reviewed twice a year", "Health insurance for you and your family", "English and tech courses paid by the company", "Hybrid schedule, 2 days remote"],
         1, 1240, 37),
    _job("Backend Developer (Python)", "IT", "TechNova Solutions", "Tashkent", 15000000, 28000000, "Full-time", "Senior",
         ["Python", "FastAPI", "PostgreSQL", "Docker", "Redis"],
         "Join the platform team that powers payments and analytics for 40+ merchants. You will design services that handle thousands of requests per second and mentor mid-level engineers.",
         ["Design and ship new microservices", "Optimise database queries and caching layers", "Set up CI/CD pipelines and monitoring", "Review architecture proposals and mentor the team"],
         ["4+ years with Python in production", "Experience with FastAPI/Django and SQLAlchemy", "Solid understanding of relational databases", "Docker and Linux experience"],
         ["Stock-option programme", "Latest MacBook Pro", "Conference and certification budget", "Flexible working hours"],
         2, 980, 24),
    _job("React Developer", "IT", "PixelCraft Studio", "Remote", 10000000, 18000000, "Contract", "Middle",
         ["React", "Next.js", "Redux", "Figma", "Jest"],
         "PixelCraft is hiring a React Developer for a 6-month contract on an international e-commerce project. Fully remote, with weekly syncs in English.",
         ["Develop reusable component libraries", "Integrate headless CMS content", "Participate in daily stand-ups in English", "Deliver features on a two-week cadence"],
         ["3+ years with React", "Next.js and SSR experience", "Comfortable working in English", "Available 30+ hours per week"],
         ["Fully remote contract", "Payment in USD", "Long-term extension possible", "Equipment allowance"],
         3, 760, 18, remote=True, currency="USD", period="month"),
    _job("Junior Software Developer", "IT", "TechNova Solutions", "Tashkent", 6000000, 9000000, "Full-time", "Junior",
         ["JavaScript", "HTML", "CSS", "Git", "SQL"],
         "A structured 12-week onboarding programme for junior developers. You will start with internal tools and grow into product work with a dedicated mentor.",
         ["Fix bugs and small features under mentorship", "Write documentation", "Participate in QA of new releases", "Grow through our internal academy"],
         ["Solid JavaScript fundamentals", "Portfolio or GitHub with pet projects", "Willingness to learn 5 days a week in the office", "Basic SQL knowledge"],
         ["Mentorship from senior engineers", "Free internal courses", "Growth plan for 12 months", "Team lunches and gym"],
         4, 1520, 64),
    _job("QA Engineer", "IT", "TechNova Solutions", "Tashkent", 9000000, 16000000, "Full-time", "Middle",
         ["Manual QA", "Postman", "SQL", "Jira", "Automation basics"],
         "Own quality for our payments module: test planning, regression, API checks and bug triage in close cooperation with developers.",
         ["Create and maintain test plans and cases", "Run functional, regression and API testing", "Report and verify bugs", "Improve QA documentation"],
         ["2+ years in manual QA of web products", "Experience with Postman and SQL", "Attention to detail", "Basic automation knowledge is a plus"],
         ["Health insurance", "Clear career ladder to Senior QA / SDET", "Paid certifications (ISTQB)", "Modern office in Tashkent"],
         5, 640, 29),
    _job("DevOps Engineer", "IT", "SilkRoute Logistics", "Tashkent", 20000000, 32000000, "Full-time", "Senior",
         ["Kubernetes", "Terraform", "AWS", "CI/CD", "Prometheus"],
         "SilkRoute is moving its logistics platform to Kubernetes. You will own infrastructure, observability and release automation for 20+ services.",
         ["Maintain Kubernetes clusters on AWS", "Automate infrastructure with Terraform", "Build release pipelines", "Set up alerting and incident response"],
         ["4+ years in DevOps/SRE", "Deep Kubernetes and Docker knowledge", "IaC experience (Terraform/Ansible)", "On-call experience"],
         ["Relocation support within Uzbekistan", "Premium insurance", "Annual salary review", "Paid AWS certifications"],
         6, 850, 15),
    _job("Python Developer (Data)", "IT", "Amu Finance Group", "Tashkent", 14000000, 24000000, "Full-time", "Middle",
         ["Python", "Pandas", "SQL", "Airflow", "Power BI"],
         "Build the data pipelines behind our risk-scoring product. You will work with analysts to turn raw banking data into decisions.",
         ["Develop ETL pipelines with Airflow", "Clean and model datasets with pandas", "Deliver dashboards for credit analysts", "Automate recurring reports"],
         ["3+ years of Python", "Strong SQL and data modelling skills", "Airflow or similar scheduler experience", "Finance domain interest"],
         ["Bonus scheme based on results", "Training budget", "Medical insurance", "Modern office near Metro"],
         7, 520, 21),

    _job("UI/UX Designer", "Design", "PixelCraft Studio", "Tashkent", 11000000, 20000000, "Full-time", "Middle",
         ["Figma", "Design systems", "Prototyping", "User research"],
         "Design end-to-end product experiences for clients in fintech, retail and education. You will own discovery, wireframes, high-fidelity UI and design hand-off.",
         ["Run discovery workshops with clients", "Create wireframes and interactive prototypes", "Maintain design systems in Figma", "Present work to stakeholders in Uzbek/Russian/English"],
         ["3+ years designing digital products", "Strong portfolio with case studies", "Figma mastery and component thinking", "Basic understanding of frontend constraints"],
         ["Hybrid schedule", "Portfolio and conference budget", "MacBook Pro + 4K monitor", "Creative, low-meeting culture"],
         2, 910, 33),
    _job("Graphic Designer", "Design", "UzDigital Marketing", "Tashkent", 7000000, 12000000, "Full-time", "Junior",
         ["Photoshop", "Illustrator", "Social media design", "Brand guidelines"],
         "Create scroll-stopping visuals for social campaigns of 15+ brands. Fast pace, high volume, strong feedback culture.",
         ["Design static and animated creatives for social media", "Adapt brand guidelines across formats", "Collaborate with SMM managers on concepts", "Prepare print-ready files"],
         ["1+ year of graphic design experience", "Strong Photoshop and Illustrator skills", "Ability to deliver 5+ creatives per day", "Portfolio required"],
         ["Performance bonus", "Paid courses", "Young team", "Free lunch on Fridays"],
         3, 780, 41),
    _job("Motion Designer", "Design", "PixelCraft Studio", "Remote", 12000000, 22000000, "Freelance", "Middle",
         ["After Effects", "Premiere Pro", "3D basics", "Storyboarding"],
         "We need a motion designer for brand films and animated explainers. Project-based cooperation with a steady pipeline of work.",
         ["Create animated explainers and brand films", "Storyboard and propose visual directions", "Export optimised assets for social platforms", "Iterate quickly with art direction"],
         ["2+ years in motion design", "Strong After Effects showreel", "Understanding of brand consistency", "Ability to work remotely on deadlines"],
         ["Project-based USD payments", "Repeat work with leading brands", "Creative freedom", "Remote-first cooperation"],
         5, 430, 12, remote=True, currency="USD", period="project"),
    _job("Product Designer", "Design", "Nexus Retail Group", "Namangan", 14000000, 24000000, "Full-time", "Senior",
         ["Figma", "User flows", "A/B testing", "Analytics"],
         "Own the design of our marketplace app used by 400k shoppers. You will work with product managers on discovery, metrics and experiments.",
         ["Lead design for the mobile marketplace", "Define user flows and information architecture", "Run usability tests and A/B experiments", "Grow and maintain the design system"],
         ["4+ years of product design experience", "Experience with mobile e-commerce", "Data-informed decision making", "Excellent communication skills"],
         ["Relocation package to Namangan", "Stock options", "Health insurance", "Quarterly team offsite"],
         8, 560, 9),

    _job("SMM Manager", "SMM", "UzDigital Marketing", "Tashkent", 8000000, 14000000, "Full-time", "Middle",
         ["Instagram", "Telegram", "Content plan", "Copywriting", "Analytics"],
         "Manage social media for 4 clients in retail and HoReCa: strategy, content plan, community management and monthly reporting.",
         ["Build monthly content plans", "Write captions in Uzbek and Russian", "Coordinate designers and video editors", "Report on reach, engagement and leads"],
         ["2+ years managing brand accounts", "Portfolio of grown accounts", "Uzbek and Russian fluency", "Understanding of paid promotion"],
         ["Bonus for hitting lead targets", "Phone and internet allowance", "Flexible start time", "Training budget"],
         1, 1120, 48),
    _job("Content Manager", "SMM", "BrightMind Academy", "Bukhara", 5000000, 9000000, "Part-time", "Junior",
         ["Content writing", "CMS", "SEO basics", "Canva"],
         "Publish and maintain learning content on our website and Telegram channel: articles, lesson summaries and student stories.",
         ["Publish 12+ pieces of content per month", "Maintain the content calendar", "Optimise posts for search", "Collect student success stories"],
         ["1 year of content experience", "Excellent Uzbek and decent English", "Basic SEO understanding", "Comfortable with CMS tools"],
         ["Part-time 4 hours per day", "Free English courses", "Friendly team", "Remote Fridays"],
         6, 390, 26, remote=True),
    _job("Digital Marketing Specialist", "Marketing", "Nexus Retail Group", "Tashkent", 11000000, 19000000, "Full-time", "Middle",
         ["Google Ads", "Meta Ads", "GA4", "KPI reporting", "CRM"],
         "Plan and run performance campaigns for our online marketplace across Google, Meta and Telegram Ads with a monthly budget of 250M UZS.",
         ["Launch and optimise paid campaigns", "Track CAC, ROAS and conversion funnels", "Run A/B tests on landing pages", "Report weekly to the CMO"],
         ["3+ years in performance marketing", "Hands-on experience with large budgets", "Strong analytics skills (GA4)", "E-commerce background preferred"],
         ["Quarterly performance bonus", "Insurance", "Modern office", "Discounts in our stores"],
         4, 690, 22),

    _job("SEO Specialist", "Marketing", "UzDigital Marketing", "Tashkent", 10000000, 17000000, "Full-time", "Middle",
         ["Technical SEO", "Ahrefs", "Keyword research", "Link building"],
         "Grow organic traffic for 8 client websites in three languages. You will own audits, content briefs and technical fixes together with developers.",
         ["Run technical SEO audits", "Build keyword maps for uz/ru/en", "Write content briefs for the copywriting team", "Monitor rankings and traffic in Ahrefs"],
         ["2+ years in SEO", "Experience with multilingual websites", "Ability to explain fixes to developers", "Analytical mindset"],
         ["Remote-friendly", "Tools budget", "Bonus for traffic growth", "Paid conferences"],
         9, 470, 14, remote=True),
    _job("Copywriter", "Marketing", "UzDigital Marketing", "Remote", 6000000, 11000000, "Freelance", "Junior",
         ["Copywriting", "Storytelling", "Ad copy", "Editing"],
         "Write landing pages, ad copy and email sequences for clients in fintech, education and retail.",
         ["Write landing page copy based on briefs", "Create ad variations for testing", "Edit and proofread team output", "Meet weekly content deadlines"],
         ["Strong Uzbek writing portfolio", "Russian and English at working level", "Ability to write in brand tones", "Reliable with deadlines"],
         ["Per-project payments", "Steady content pipeline", "Fully remote", "Feedback and mentoring"],
         11, 520, 35, remote=True, currency="UZS", period="project"),

    _job("Sales Manager", "Sales", "Nexus Retail Group", "Tashkent", 12000000, 30000000, "Full-time", "Middle",
         ["B2B sales", "Negotiation", "CRM", "Pipeline management"],
         "Own a portfolio of corporate clients and grow wholesale revenue. Strong commission, clear KPI and a real career path.",
         ["Grow the existing client portfolio", "Negotiate supply contracts", "Keep CRM records accurate", "Hit monthly revenue targets"],
         ["3+ years in B2B sales", "Proven negotiation skills", "Uzbek and Russian fluency", "Self-driven and target-oriented"],
         ["Uncapped commission (up to 100% of salary)", "Company car for client visits", "Mobile allowance", "Quarterly incentives"],
         3, 830, 27),
    _job("Sales Representative", "Sales", "MedLine Care", "Andijan", 7000000, 15000000, "Full-time", "Junior",
         ["Direct sales", "Customer service", "Reporting"],
         "Represent MedLine Care services to corporate clients in the Fergana valley: presentations, contracts and after-sales support.",
         ["Visit 8-10 potential clients per day", "Present service packages", "Sign service agreements", "Report daily in CRM"],
         ["1+ year in sales or customer service", "Confident communication", "Driver licence preferred", "Uzbek and Russian"],
         ["Base salary + monthly bonus", "Fuel compensation", "Training programme", "Health check-ups"],
         7, 410, 19),
    _job("Business Development Manager", "Sales", "TechNova Solutions", "Tashkent", 18000000, 35000000, "Full-time", "Senior",
         ["Partnerships", "Strategy", "B2B", "Fintech"],
         "Open new markets for our fintech platform: partnerships with banks, payment providers and large merchants across the region.",
         ["Build a partner pipeline", "Negotiate commercial terms", "Represent the company at industry events", "Work with product on roadmap inputs"],
         ["5+ years in BD or enterprise sales", "Network in banking/payments", "English upper-intermediate+", "Analytical, deal-closing mindset"],
         ["Equity package", "Business trips budget", "Premium insurance", "Direct line to the founders"],
         10, 620, 11),

    _job("Accountant", "Finance", "Amu Finance Group", "Tashkent", 9000000, 16000000, "Full-time", "Middle",
         ["1C", "Tax reporting", "Payroll", "Excel"],
         "Full-cycle accounting for a group of client companies: primary documents, payroll, tax reports and audits.",
         ["Maintain accounting records in 1C", "Prepare monthly and quarterly tax reports", "Process payroll for 120 employees", "Support external audits"],
         ["3+ years as an accountant", "Strong 1C and Excel skills", "Knowledge of Uzbek tax legislation", "Accuracy and reliability"],
         ["Stable schedule 9-18", "Medical insurance", "Paid vacation 24 days", "Professional certification support"],
         5, 340, 16),
    _job("Financial Analyst", "Finance", "Amu Finance Group", "Tashkent", 15000000, 25000000, "Full-time", "Middle",
         ["Financial modelling", "Excel", "SQL", "Valuation"],
         "Support investment decisions with models, market research and portfolio reporting for our client funds.",
         ["Build financial models and scenarios", "Prepare investment memos", "Monitor portfolio performance", "Automate reporting with SQL"],
         ["2+ years in financial analysis", "Advanced Excel modelling", "CFA level 1+ is a plus", "English upper-intermediate"],
         ["CFA sponsorship", "Bonus scheme", "Hybrid schedule", "Mentorship from partners"],
         12, 380, 13),

    _job("English Teacher", "Education", "BrightMind Academy", "Bukhara", 6000000, 11000000, "Full-time", "Junior",
         ["IELTS", "Classroom management", "Lesson planning"],
         "Teach general and IELTS English to groups of 8-12 students in our modern Bukhara campus with an interactive whiteboard in every classroom.",
         ["Deliver 20-24 lessons per week", "Prepare students for IELTS 6.5+", "Track attendance and progress", "Participate in weekly methodology meetings"],
         ["CEFR C1 or above", "TEFL/CELTA certificate preferred", "1+ year teaching experience", "Energetic, student-centred approach"],
         ["Methodology training", "Free IELTS exam", "Paid vacation", "Career path to senior teacher"],
         2, 450, 31),
    _job("Math Teacher", "Education", "BrightMind Academy", "Samarkand", 6000000, 10000000, "Full-time", "Middle",
         ["Mathematics", "Lesson planning", "Olympiad prep"],
         "Prepare 9-11 grade students for university entrance exams and national olympiads.",
         ["Teach maths to exam groups", "Design test materials", "Run monthly mock exams", "Coach olympiad candidates"],
         ["Higher education in mathematics", "2+ years of teaching experience", "Strong results with exam groups", "Patient communicator"],
         ["Free courses for your children", "Performance bonus", "Friendly atmosphere", "Modern classrooms"],
         8, 300, 17),
    _job("IT Instructor", "Education", "BrightMind Academy", "Bukhara", 9000000, 17000000, "Contract", "Middle",
         ["Python", "JavaScript", "Teaching", "Curriculum design"],
         "Teach our full-stack bootcamp: 4 evenings per week, groups of 15 students, project-based curriculum.",
         ["Deliver Python and JavaScript lessons", "Review student projects", "Improve the curriculum", "Support students during job search"],
         ["2+ years in web development", "Experience teaching or mentoring", "Clear communication in Uzbek", "Portfolio of shipped projects"],
         ["Competitive contract rate", "Curriculum is ready to use", "Evening schedule (18:00-21:00)", "Become part of a growing academy"],
         13, 280, 22),
]

JOBS += [
    _job("Customer Support Specialist", "Support", "Nexus Retail Group", "Tashkent", 6000000, 10000000, "Full-time", "No experience",
         ["Communication", "CRM", "Problem solving", "Uzbek/Russian"],
         "Be the first friendly voice our shoppers hear. Handle chats and calls about orders, payments and returns.",
         ["Answer customer chats and calls", "Process returns and complaints", "Keep CRM tickets up to date", "Escalate complex cases"],
         ["No experience required, full training provided", "Clear career path to team lead", "Friendly young team", "Free lunch in the office"],
         ["Excellent Uzbek and Russian", "Basic computer skills", "Polite and patient communication", "Ready for shift work"],
         1, 960, 58),
    _job("Call Center Operator", "Support", "MedLine Care", "Andijan", 5000000, 8500000, "Part-time", "No experience",
         ["Phone etiquette", "Booking systems", "Empathy"],
         "Help patients book appointments and answer questions about our clinic services over the phone.",
         ["Handle incoming calls", "Book and reschedule appointments", "Inform patients about services", "Log every call in the system"],
         ["Part-time 6 hours per day", "Shift bonuses", "Supportive mentors", "Free annual medical check-up"],
         ["Clear speaking voice", "Uzbek and Russian fluency", "Basic computer skills", "Willingness to work in shifts"],
         4, 520, 44),
    _job("Office Administrator", "Operations", "Amu Finance Group", "Tashkent", 6000000, 9500000, "Full-time", "Junior",
         ["Office management", "MS Office", "Documentation", "Scheduling"],
         "Keep our head office running smoothly: documents, supplies, visitors and the small things that make work pleasant.",
         ["Manage incoming and outgoing documentation", "Coordinate office supplies and vendors", "Greet guests and manage meeting rooms", "Support HR with onboarding paperwork"],
         ["Stable schedule 9:00-18:00", "Medical insurance", "Friendly team culture", "Annual performance bonus"],
         ["1+ year in an office role", "Organised and proactive", "Confident MS Office user", "Uzbek and Russian"],
         6, 410, 25),
    _job("Project Manager", "Operations", "TechNova Solutions", "Tashkent", 16000000, 28000000, "Full-time", "Senior",
         ["Agile", "Scrum", "Jira", "Stakeholder management"],
         "Lead two product squads delivering our marketplace and payments roadmap. You will own delivery, risks and client communication.",
         ["Facilitate sprint planning and reviews", "Track scope, risks and dependencies", "Report to stakeholders weekly", "Continuously improve delivery processes"],
         ["Leadership training budget", "Health insurance for the family", "Hybrid schedule", "Yearly performance bonus"],
         ["4+ years in IT project management", "Hands-on Scrum experience", "Excellent English", "Technical background preferred"],
         9, 540, 8),
    _job("Logistics Coordinator", "Logistics", "SilkRoute Logistics", "Samarkand", 8000000, 13000000, "Full-time", "Middle",
         ["Route planning", "Customs documents", "Excel", "Supplier communication"],
         "Coordinate cargo movements between Tashkent, Samarkand and the Chinese border, keeping clients informed at every step.",
         ["Plan routes and book transport", "Prepare customs documentation", "Monitor shipments and resolve delays", "Report daily to the operations lead"],
         ["Transport compensation", "Annual bonus", "Paid overtime hours", "Growth to senior coordinator"],
         ["2+ years in logistics", "Knowledge of customs procedures", "Strong Excel skills", "English at working level"],
         5, 350, 20),
    _job("Delivery Coordinator", "Logistics", "Nexus Retail Group", "Namangan", 6000000, 10000000, "Full-time", "Junior",
         ["Dispatching", "Excel", "Customer service", "GPS systems"],
         "Coordinate 40+ couriers per shift, optimise delivery routes and keep customers informed about their orders.",
         ["Assign orders to couriers", "Monitor delivery times", "Handle failed deliveries", "Report daily KPIs"],
         ["Shift bonuses", "Free lunch", "Career growth in operations", "Modern office in the city centre"],
         ["1+ year in operations or dispatching", "Comfortable with software tools", "Stress resistant", "Driver licence is a plus"],
         10, 380, 23),
    _job("Warehouse Supervisor", "Operations", "SilkRoute Logistics", "Tashkent", 9000000, 14000000, "Full-time", "Middle",
         ["Inventory management", "Team leadership", "WMS", "Safety"],
         "Supervise a 4,000 m2 warehouse: inbound, picking, packing and inventory accuracy with a team of 25 people.",
         ["Plan daily workloads", "Keep inventory accuracy above 99%", "Enforce safety rules", "Report to the operations manager"],
         ["Shift allowance", "Medical insurance", "Quarterly team bonus", "On-site canteen"],
         ["3+ years in warehouse operations", "Team leadership experience", "WMS knowledge", "Ready for an active role"],
         14, 290, 15),

    _job("Photographer", "Media", "PixelCraft Studio", "Tashkent", 7000000, 13000000, "Freelance", "Middle",
         ["Product photography", "Lightroom", "Studio lighting", "Retouching"],
         "Shoot product, food and lifestyle content for our retail and HoReCa clients in our studio and on location.",
         ["Plan shoots with art directors", "Produce 250+ retouched photos per month", "Maintain studio equipment", "Deliver within feedback rounds"],
         ["Project-based payments", "Studio and lighting equipment provided", "Repeat work with leading brands", "Creative freedom"],
         ["Strong portfolio of commercial shoots", "Own camera body", "Confident Lightroom skills", "Flexible schedule"],
         7, 430, 27, currency="UZS", period="project"),
    _job("Video Editor", "Media", "UzDigital Marketing", "Remote", 8000000, 15000000, "Contract", "Middle",
         ["Premiere Pro", "DaVinci Resolve", "Sound design", "Subtitles"],
         "Edit 20+ short-form videos per month for TikTok, Reels and YouTube Shorts across six brands.",
         ["Edit short-form vertical videos", "Add motion titles and subtitles", "Follow brand guidelines", "Deliver three rounds of revisions"],
         ["Fully remote cooperation", "Per-video rates in UZS", "Fast-growing content pipeline", "Equipment upgrade support"],
         ["2+ years editing social video", "Strong storytelling skills", "Own workstation", "Reliable with deadlines"],
         3, 640, 34, remote=True, currency="UZS", period="project"),
    _job("HR Specialist", "HR", "MedLine Care", "Andijan", 8000000, 13000000, "Full-time", "Middle",
         ["Recruitment", "HR documentation", "Onboarding", "Labour law"],
         "Own the employee lifecycle for 140 people: hiring, onboarding, records, evaluation and offboarding.",
         ["Run end-to-end recruitment", "Prepare HR documentation", "Organise onboarding and training", "Support managers with performance reviews"],
         ["Insurance for the whole family", "Annual training budget", "Stable schedule", "Supportive HR team"],
         ["2+ years in HR", "Knowledge of Uzbek labour legislation", "Strong communication skills", "High level of confidentiality"],
         11, 330, 19),
    _job("Recruiter", "HR", "TechNova Solutions", "Tashkent", 10000000, 18000000, "Full-time", "Middle",
         ["Tech recruitment", "Sourcing", "LinkedIn", "Interviewing"],
         "Hire 30+ engineers this year. You will own sourcing, screening, scheduling and the whole candidate experience.",
         ["Source candidates via LinkedIn and Telegram", "Screen and schedule interviews", "Maintain the ATS", "Improve employer branding"],
         ["Bonus for every successful hire", "Hybrid schedule", "LinkedIn Recruiter seat", "HR education budget"],
         ["2+ years recruiting IT talent", "English upper-intermediate", "Strong interview skills", "Data-driven approach"],
         2, 480, 26),

    _job("Barista", "Hospitality", "Nexus Retail Group", "Tashkent", 5000000, 8000000, "Part-time", "No experience",
         ["Coffee preparation", "Customer service", "Cash handling"],
         "Serve great coffee with a smile in our flagship store on Amir Temur avenue. Full training provided.",
         ["Prepare espresso-based drinks", "Take orders and handle payments", "Keep the bar clean and stocked", "Recommend bakery items"],
         ["Free coffee and pastries during shifts", "Flexible shift schedule", "Barista certification", "Team tips shared daily"],
         ["Friendly and energetic personality", "Uzbek and Russian", "Ready for morning shifts", "Hygiene awareness"],
         1, 700, 52),
    _job("Restaurant Manager", "Hospitality", "Nexus Retail Group", "Samarkand", 12000000, 20000000, "Full-time", "Senior",
         ["Team management", "P&L", "F&B operations", "Customer experience"],
         "Lead a 45-seat restaurant with 22 staff members: service quality, financial results and team development.",
         ["Manage daily operations and staff rota", "Control food cost and P&L", "Uphold service standards", "Recruit and train the team"],
         ["Performance bonus", "Meals provided", "Medical insurance", "Career growth inside our group"],
         ["4+ years in F&B management", "P&L responsibility experience", "Leadership and coaching skills", "HACCP knowledge"],
         12, 260, 10),
]

DEMO_JOB_SEEKER = {
    "name": "Aziz Karimov",
    "email": "demo@localjob.uz",
    "password": "Demo1234!",
    "role": "job_seeker",
    "phone": "+998 90 123 45 67",
    "location": "Tashkent",
    "profile": {
        "title": "Frontend Developer (React / TypeScript)",
        "bio": "Frontend developer with 3 years of experience building web applications with React and TypeScript. I enjoy turning complex interfaces into simple, fast and accessible products. Currently improving my Node.js skills.",
        "category": "IT",
        "skills": ["React", "TypeScript", "Tailwind CSS", "Redux", "REST API", "Git", "Figma", "Jest"],
        "experience": [
            {"role": "Frontend Developer", "company": "UzDigital Marketing", "from": "2023-02", "to": "present",
             "description": "Built landing pages and dashboards for 12 client projects with React and TypeScript. Improved average Lighthouse performance score from 62 to 94."},
            {"role": "Junior Frontend Developer", "company": "StartUp Lab", "from": "2022-01", "to": "2023-01",
             "description": "Worked on an internal CRM interface, fixed bugs and wrote first unit tests with Jest."},
        ],
        "education": [
            {"degree": "BSc Computer Science", "school": "Tashkent University of Information Technologies", "from": "2018", "to": "2022"},
        ],
        "languages": ["Uzbek (native)", "Russian (fluent)", "English (B2)"],
        "portfolio": "https://aziz.dev",
        "github": "https://github.com/azizkarimov",
        "linkedin": "https://linkedin.com/in/azizkarimov",
        "telegram": "https://t.me/aziz_dev",
        "experience_level": "Middle",
        "expected_salary": 18000000,
    },
}

DEMO_EMPLOYER = {
    "name": "Dilnoza Yusupova",
    "email": "employer@localjob.uz",
    "password": "Demo1234!",
    "role": "employer",
    "phone": "+998 71 200 30 40",
    "location": "Tashkent",
    "company": "TechNova Solutions",
}

ADMIN_USER = {
    "name": "LocalJob Admin",
    "email": "admin@localjob.uz",
    "password": "Admin1234!",
    "role": "admin",
    "location": "Tashkent",
}

# Demo applications created for the demo job seeker so /applications is not empty
DEMO_APPLICATION_TITLES = [
    ("Frontend Developer", "I have 3 years of hands-on React experience and recently led the migration of a legacy dashboard to TypeScript. I would love to bring that experience to TechNova."),
    ("React Developer", "Your e-commerce project matches my recent work almost exactly. I am available 35 hours per week and comfortable working in English."),
]
DEMO_SAVED_TITLES = ["Backend Developer (Python)", "UI/UX Designer", "DevOps Engineer", "SMM Manager"]

DEMO_NOTIFICATIONS = [
    ("success", "Application submitted", "Your application for Frontend Developer at TechNova Solutions was submitted successfully.", "/applications", 1),
    ("info", "Status changed", "Your application for React Developer was moved to Shortlisted.", "/applications", 3),
    ("job", "New jobs matching your profile", "12 new IT jobs in Tashkent were published this week.", "/jobs?category=IT", 5),
]
